
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felipe
 */
public class gradeUpGUI extends javax.swing.JFrame {
    
    private ArrayList<asignatura> asignaturas;
    private double promedio;
    private int cantAsg;
    private DefaultListModel modeloNotas1;
    /**
     * Creates new form gradeUpGUI
     */
    public gradeUpGUI() {
        asignaturas = new ArrayList<asignatura>();
        cantAsg = 0;
        this.modeloNotas1 = new DefaultListModel();
        initComponents();
        bAgregarNota1.setVisible(false);
        bBorrarNota1.setVisible(false);
        bCambiarNota1.setVisible(false);
        bPromediar1.setVisible(false);
        bBorrarAs1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabAsignatura = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        bPromediar1 = new javax.swing.JButton();
        resultado1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        asg1Label = new javax.swing.JLabel();
        inNota1 = new javax.swing.JTextField();
        inPorc1 = new javax.swing.JTextField();
        inDesc1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNotasAs1 = new javax.swing.JList();
        bAgregarNota1 = new javax.swing.JButton();
        bBorrarNota1 = new javax.swing.JButton();
        bCambiarNota1 = new javax.swing.JButton();
        bBorrarAs1 = new javax.swing.JButton();
        horasL1 = new javax.swing.JLabel();
        porcAsisL1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        asg2Label = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        asg3Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        agregarAsignatura = new javax.swing.JButton();
        nombreAsig = new javax.swing.JTextField();
        horasAsig = new javax.swing.JTextField();
        salirBoton = new javax.swing.JButton();
        asisAsig = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        tabAsignatura.setBackground(new java.awt.Color(255, 255, 0));
        tabAsignatura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel1.setBackground(new java.awt.Color(255, 204, 102));

        bPromediar1.setText("Promediar");
        bPromediar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPromediar1ActionPerformed(evt);
            }
        });

        resultado1.setText("Resultado");

        jLabel17.setBackground(new java.awt.Color(255, 255, 102));
        jLabel17.setText("Notas");

        jLabel18.setText("Porcentaje");

        jLabel19.setText("Descripción");

        asg1Label.setText("--");

        inNota1.setText("--");
        inNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNota1ActionPerformed(evt);
            }
        });

        inPorc1.setText("--");
        inPorc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPorc1ActionPerformed(evt);
            }
        });

        inDesc1.setText("--");
        inDesc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDesc1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaNotasAs1);

        bAgregarNota1.setText("Agregar nota");
        bAgregarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarNota1ActionPerformed(evt);
            }
        });

        bBorrarNota1.setText("Borrar nota");
        bBorrarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarNota1ActionPerformed(evt);
            }
        });

        bCambiarNota1.setText("Cambiar nota");
        bCambiarNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarNota1ActionPerformed(evt);
            }
        });

        bBorrarAs1.setText("Borrar asignatura");

        horasL1.setText("--");

        porcAsisL1.setText("--");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addComponent(inPorc1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(inDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(horasL1)
                                .addComponent(porcAsisL1))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(bPromediar1)
                        .addGap(77, 77, 77)
                        .addComponent(resultado1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bAgregarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBorrarNota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bCambiarNota1)
                    .addComponent(bBorrarAs1))
                .addGap(31, 31, 31))
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(asg1Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asg1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horasL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porcAsisL1)
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inPorc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAgregarNota1))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(bCambiarNota1)
                        .addGap(16, 16, 16)
                        .addComponent(bBorrarNota1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPromediar1)
                    .addComponent(resultado1)
                    .addComponent(bBorrarAs1))
                .addGap(25, 25, 25))
        );

        tabAsignatura.addTab("Asignatura 1", panel1);

        panel2.setBackground(new java.awt.Color(255, 204, 102));

        asg2Label.setText("Asignatura 2");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asg2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 294, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asg2Label)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        tabAsignatura.addTab("Asignatura 2", panel2);

        panel3.setBackground(new java.awt.Color(255, 204, 102));

        asg3Label.setText("Asignatura 3");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asg3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 294, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(asg3Label)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        tabAsignatura.addTab("Asignatura 3", panel3);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felipe\\Desktop\\Grade-Up 100x100.png")); // NOI18N

        agregarAsignatura.setText("Agregar asignatura");
        agregarAsignatura.setToolTipText("");
        agregarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAsignaturaActionPerformed(evt);
            }
        });

        nombreAsig.setText("Nombre");

        horasAsig.setText("Horas");

        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });

        asisAsig.setText("% Asistencia");

        jButton5.setText("Guardar datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarAsignatura, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(salirBoton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addComponent(horasAsig))
                            .addComponent(jButton5)
                            .addComponent(asisAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tabAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addComponent(agregarAsignatura)
                        .addGap(42, 42, 42)
                        .addComponent(nombreAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(horasAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(asisAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(salirBoton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAsignatura.getAccessibleContext().setAccessibleName("Asignatura 1");
        tabAsignatura.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAsignaturaActionPerformed
        asignatura asignaturaNueva = new asignatura(nombreAsig.getText(), Integer.parseInt(horasAsig.getText()), Double.parseDouble(asisAsig.getText()));
        asignaturas.add(asignaturaNueva);
        cantAsg += 1;
        switch (cantAsg){
            case 1:
                bAgregarNota1.setVisible(true);
                bBorrarNota1.setVisible(true);
                bCambiarNota1.setVisible(true);
                bPromediar1.setVisible(true);
                bBorrarAs1.setVisible(true);
                asg1Label.setText(asignaturas.get(0).getNombreAsignatura());
                horasL1.setText("Horas: " + asignaturas.get(0).getHoras());
                porcAsisL1.setText("Porcentaje de asistencia: " + asignaturas.get(0).getPorcentajeasis());
                inNota1.setText("0.0");
                inPorc1.setText("0.0");
                inDesc1.setText("Primera prueba");
                break;
                
            case 2:
                panel2.setVisible(true);
                asg2Label.setText(asignaturas.get(1).getNombreAsignatura());
                break;
            case 3:
                panel2.setVisible(true);
                asg3Label.setText(asignaturas.get(2).getNombreAsignatura());
                break;
            
            default:
                break;
        }
    }//GEN-LAST:event_agregarAsignaturaActionPerformed
    
    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        //GENERAR TXT
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void bPromediar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPromediar1ActionPerformed
        String prom = "" + asignaturas.get(0).calcularPromedio() + " ";
        resultado1.setText(prom.substring(0, 4));
    }//GEN-LAST:event_bPromediar1ActionPerformed

    private void inDesc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDesc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDesc1ActionPerformed

    private void inPorc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPorc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inPorc1ActionPerformed

    private void inNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNota1ActionPerformed

    private void bAgregarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarNota1ActionPerformed
        double agregarNota = Double.parseDouble(inNota1.getText());
        double agregarPorcentaje = Double.parseDouble(inPorc1.getText());
        String agregarDescripción = inDesc1.getText();
        nota nuevaNota = new nota(agregarNota, agregarPorcentaje, agregarDescripción);
        asignaturas.get(0).getNotas().add(nuevaNota);
        modeloNotas1.addElement(agregarNota + " " + agregarPorcentaje + "% " + agregarDescripción);
        listaNotasAs1.setModel(modeloNotas1);
    }//GEN-LAST:event_bAgregarNota1ActionPerformed

    private void bCambiarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarNota1ActionPerformed
        double cambiarNota = Double.parseDouble(inNota1.getText());
        double cambiarPorcentaje = Double.parseDouble(inPorc1.getText());
        String cambiarDescripción = inDesc1.getText();
        int index = listaNotasAs1.getSelectedIndex();
        asignaturas.get(0).getNotas().get(index).setNota(cambiarNota);
        asignaturas.get(0).getNotas().get(index).setPorcentaje(cambiarPorcentaje);
        asignaturas.get(0).getNotas().get(index).setDescripcion(cambiarDescripción);
        String cambio = cambiarNota + " " + cambiarPorcentaje + "% " + cambiarDescripción;
        modeloNotas1.setElementAt(cambio, index);
    }//GEN-LAST:event_bCambiarNota1ActionPerformed

    private void bBorrarNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarNota1ActionPerformed
        int index = listaNotasAs1.getSelectedIndex();
        modeloNotas1.remove(index);
        asignaturas.get(0).getNotas().remove(index);
    }//GEN-LAST:event_bBorrarNota1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAsignatura;
    private javax.swing.JLabel asg1Label;
    private javax.swing.JLabel asg2Label;
    private javax.swing.JLabel asg3Label;
    private javax.swing.JTextField asisAsig;
    private javax.swing.JButton bAgregarNota1;
    private javax.swing.JButton bBorrarAs1;
    private javax.swing.JButton bBorrarNota1;
    private javax.swing.JButton bCambiarNota1;
    private javax.swing.JButton bPromediar1;
    private javax.swing.JTextField horasAsig;
    private javax.swing.JLabel horasL1;
    private javax.swing.JTextField inDesc1;
    private javax.swing.JTextField inNota1;
    private javax.swing.JTextField inPorc1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaNotasAs1;
    private javax.swing.JTextField nombreAsig;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel porcAsisL1;
    private javax.swing.JLabel resultado1;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTabbedPane tabAsignatura;
    // End of variables declaration//GEN-END:variables
}
