/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marcos
 */
public class Guibienvenida extends javax.swing.JFrame {
    private String nombreal;
    private String institucion;
    private boolean visibilidad;

    public String getNombreal() {
        return nombreal;
    }

    public void setNombreal(String nombreal) {
        this.nombreal = nombreal;
    }

    public String getInstitucion() {
        return institucion;
    }

    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    /**
     * Creates new form Guibienvenida
     */
    public Guibienvenida() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnombre = new javax.swing.JLabel();
        labelinstitucion = new javax.swing.JLabel();
        textfieldnombre = new javax.swing.JTextField();
        textfieldinstitucion = new javax.swing.JTextField();
        buttoncontinue = new javax.swing.JButton();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelnombre.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        labelnombre.setText("Nombre:");
        getContentPane().add(labelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 70, 19));

        labelinstitucion.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        labelinstitucion.setText("Institucion:");
        getContentPane().add(labelinstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 70, -1));

        textfieldnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldnombreActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, -1));
        getContentPane().add(textfieldinstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, -1));

        buttoncontinue.setBackground(new java.awt.Color(0, 0, 0));
        buttoncontinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn_continuar.png"))); // NOI18N
        buttoncontinue.setBorder(null);
        buttoncontinue.setBorderPainted(false);
        buttoncontinue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttoncontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncontinueActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncontinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 220, 50));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guiprincipal.png"))); // NOI18N
        getContentPane().add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldnombreActionPerformed

    private void buttoncontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncontinueActionPerformed
        // TODO add your handling code here:
        this.nombreal=textfieldnombre.getText();
        this.institucion=textfieldinstitucion.getText();
        this.visibilidad=false;
        
    }//GEN-LAST:event_buttoncontinueActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncontinue;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelinstitucion;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JTextField textfieldinstitucion;
    private javax.swing.JTextField textfieldnombre;
    // End of variables declaration//GEN-END:variables
}
